In [2]:
import pandas as pd
import numpy as np

print("Libraries imported successfully!")

Libraries imported successfully!

In [ ]:
# Path to the first file
file_path = '/content/drive/MyDrive/2025 김진영교수 연구참여/2차 요청자료/부처별 사업정리_김준수(1-4).xlsx'

# Load sheet 5 (using index 4 as sheets are 0-indexed)
try:
    df_sheet5 = pd.read_excel(file_path, sheet_name=4)
    print(f"Data loaded successfully from sheet 5 of {file_path}")
    print(f"Sheet 5 data shape: {df_sheet5.shape}")
    print("\nSheet 5 Head:")
    print(df_sheet5.head())
except FileNotFoundError:
    print(f"Error: File not found at {file_path}. Please check the path and upload the file to your Google Drive.")
except Exception as e:
    print(f"An error occurred while loading the data: {e}")

Error: File not found at /content/drive/MyDrive/2025 김진영교수 연구참여/2차 요청자료/부처별 사업정리_김준수(1-4).xlsx. Please check the path and upload the file to your Google Drive.

# Task
Read the first column of sheet1 and sheet2 from the file "/content/drive/MyDrive/2025 김진영교수 연구참여/산림복지사업군2차요청자료(0825)/02_산림청/4. 산림교육치유활성화/심층평가 2차 자료(산림교육치유활성화).xlsx", and the names of sheet1 and sheet2. Then, insert the sheet names followed by the first column data into the '구분' column of sheet5 in the file "/content/drive/MyDrive/2025 김진영교수 연구참여/산림복지사업군2차요청자료(0825)/부처별 사업정리.xlsx".

## Load specific sheets from the second file

### Subtask:
Load sheet1 and sheet2 from the second file.

**Reasoning**:
Load Sheet1 and Sheet2 from the second file using pandas ExcelFile object.

In [ ]:
second_file_path = '/content/drive/MyDrive/2025 김진영교수 연구참여/산림복지사업군2차요청자료(0825)/02_산림청/4. 산림교육치유활성화/심층평가 2차 자료(산림교육치유활성화).xlsx'

try:
    excel_file = pd.ExcelFile(second_file_path)
    print("Sheet names in the second file:")
    print(excel_file.sheet_names)

except FileNotFoundError:
    print(f"Error: File not found at {second_file_path}. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the data: {e}")

Sheet names in the second file:
['유아숲체험원', '치유의 숲 1', '치유의 숲 2', 'Sheet1', '1(2)']

**Reasoning**:
Based on the sheet names, I will load the sheets named '유아숲체험원' and '치유의 숲 1' which seem to correspond to the first and second sheets, and print their head and shape.

In [ ]:
second_file_path = '/content/drive/MyDrive/2025 김진영교수 연구참여/산림복지사업군2차요청자료(0825)/02_산림청/4. 산림교육치유활성화/심층평가 2차 자료(산림교육치유활성화).xlsx'

try:
    excel_file = pd.ExcelFile(second_file_path)
    df_sheet1_second_file = excel_file.parse('유아숲체험원')
    df_sheet2_second_file = excel_file.parse('치유의 숲 1')

    print("Sheet '유아숲체험원' Head:")
    display(df_sheet1_second_file.head())
    print(f"\nSheet '유아숲체험원' Shape: {df_sheet1_second_file.shape}")

    print("\nSheet '치유의 숲 1' Head:")
    display(df_sheet2_second_file.head())
    print(f"\nSheet '치유의 숲 1' Shape: {df_sheet2_second_file.shape}")

except FileNotFoundError:
    print(f"Error: File not found at {second_file_path}. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the data: {e}")

Sheet '유아숲체험원' Head:

,"<산림교육치유활성화 사업> 유아숲체험원 명단, 소재지, 방문객, 예산외 수입, 비용항목별 액수",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,유아숲체험원 명,소재지,예산(백만원),교육인원,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,예산외수입,비용항목별 액수(백만원) \n<보험료 등 공과금>
2,NaN,NaN,NaN,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년,2023년,2024년,2025년,NaN,NaN
3,서울숲공원 유아숲체험원,서울특별시 성동구 성수1가 685-124,100,-,-,-,-,-,-,1391,3521,3192,3475,1535,-,-
4,한남 유아숲체험원,서울특별시 용산구 한남동 772-1,301,912,26879,21381,18000,15323,634,10349,29708,19412,21671,6658,-,-

Sheet '유아숲체험원' Shape: (489, 16)

Sheet '치유의 숲 1' Head:

,"<산림교육치유활성화 사업> 치유의 숲 명단, 예산외 수입, 비용항목별 액수",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,치유의 숲 명,소재지,예산외 수입(백만원),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,비용항목별 액수(백만원) \n<보험료 등 공과금>,비고
2,NaN,NaN,2015년,2016년,2017년,2018년,2019년,2020년,2021년,2022년,2023년,2024년,2025년 6월,NaN,NaN
3,산음 치유의 숲,경기 양평군 단월면 고북길 347,2.71,6.166,5.5765,2.916,3.059,0.328,0.7455,2.2595,2.9705,1.2105,0.574,-,국립
4,양평 치유의 숲,경기 양평군 양동면 황거길 262-10,0,0,0,43.445,49.161,22.864,65.035,66.4585,85.9485,76.314,70.1466,-,국립

Sheet '치유의 숲 1' Shape: (57, 15)

## Extract sheet names

### Subtask:
Get the names of sheet1 ('유아숲체험원') and sheet2 ('치유의 숲 1') from the second file.

**Reasoning**:
Create a list with the specified sheet names and store it in the `sheet_names` variable.

In [ ]:
sheet_names = ['유아숲체험원', '치유의 숲 1']
print(f"Sheet names: {sheet_names}")

Sheet names: ['유아숲체험원', '치유의 숲 1']

## Extract first column data

### Subtask:
Get the data from the first column of sheet1 and sheet2.

**Reasoning**:
Extract the data from the first column of `df_sheet1_second_file` and `df_sheet2_second_file` and store them in separate variables, then display the head of both extracted columns.

In [ ]:
first_column_sheet1 = df_sheet1_second_file.iloc[3:, 0]
first_column_sheet2 = df_sheet2_second_file.iloc[3:, 0]

print("Head of the first column of sheet '유아숲체험원':")
display(first_column_sheet1.head())

print("\nHead of the first column of sheet '치유의 숲 1':")
display(first_column_sheet2.head())

Head of the first column of sheet '유아숲체험원':

3     서울숲공원 유아숲체험원
4        한남 유아숲체험원
5     보라매공원 유아숲체험원
6     월드컵공원 유아숲체험원
7    북서울꿈의숲 유아숲체험원
Name: <산림교육치유활성화 사업> 유아숲체험원 명단, 소재지, 방문객, 예산외 수입, 비용항목별 액수, dtype: object

Head of the first column of sheet '치유의 숲 1':

3     산음 치유의 숲
4     양평 치유의 숲
5    청태산 치유의 숲
6    대관령 치유의 숲
7      예산치유의숲
Name: <산림교육치유활성화 사업> 치유의 숲 명단, 예산외 수입, 비용항목별 액수, dtype: object

## Prepare data for insertion

### Subtask:
Combine the extracted sheet names and first column data in a format suitable for insertion.

**Reasoning**:
Combine the sheet names and the first column data into a single list and then convert it to a pandas Series.

In [ ]:
combined_list = first_column_sheet1.tolist() + first_column_sheet2.tolist()
combined_data = pd.Series(combined_list)
display(combined_data.head())

0     서울숲공원 유아숲체험원
1        한남 유아숲체험원
2     보라매공원 유아숲체험원
3     월드컵공원 유아숲체험원
4    북서울꿈의숲 유아숲체험원
dtype: object

## Extract '소재지' column

### Subtask:
Get the data from the '소재지' column from the relevant sheets of the second file, ensuring alignment with the names already inserted into `df_sheet5`.

**Reasoning**:
Extract the data from the second column ('Unnamed: 1') of `df_sheet1_second_file` and `df_sheet2_second_file`, starting from row 3 (index 3) to match the rows containing the names. Store these in separate variables and display their heads to verify the extraction.

In [ ]:
# Extract '소재지' column (index 1) starting from row 3 (index 3)
location_sheet1 = df_sheet1_second_file.iloc[3:, 1]
location_sheet2 = df_sheet2_second_file.iloc[3:, 1]

print("Head of the '소재지' column of sheet '유아숲체험원':")
display(location_sheet1.head())

print("\nHead of the '소재지' column of sheet '치유의 숲 1':")
display(location_sheet2.head())

Head of the '소재지' column of sheet '유아숲체험원':

3    서울특별시 성동구 성수1가 685-124
4       서울특별시 용산구 한남동 772-1
5       서울특별시 동작구 신대방동 산143
6        서울특별시 마포구 상암동 1538
7           서울특별시 강북구 번동 90
Name: Unnamed: 1, dtype: object

Head of the '소재지' column of sheet '치유의 숲 1':

3          경기 양평군 단월면 고북길 347
4       경기 양평군 양동면 황거길 262-10
5        강원 횡성군 둔내면 청태산로 777
6    강원 강릉시 성산면 대관령옛길 127-42
7      충남 예산군 예산읍 치유숲길 203-31
Name: Unnamed: 1, dtype: object

## Combine '소재지' data

### Subtask:
Combine the extracted '소재지' data from both sheets into a single Series.

**Reasoning**:
Concatenate the `location_sheet1` and `location_sheet2` Series into a single Series called `combined_locations`.

In [ ]:
combined_locations = pd.concat([location_sheet1, location_sheet2], ignore_index=True)
print("Head of the combined '소재지' data:")
display(combined_locations.head())

print("\nTail of the combined '소재지' data:")
display(combined_locations.tail())

print(f"\nShape of combined '소재지' data: {combined_locations.shape}")

Head of the combined '소재지' data:

0    서울특별시 성동구 성수1가 685-124
1       서울특별시 용산구 한남동 772-1
2       서울특별시 동작구 신대방동 산143
3        서울특별시 마포구 상암동 1538
4           서울특별시 강북구 번동 90
Name: Unnamed: 1, dtype: object

Tail of the combined '소재지' data:

535     경남 거창군 가조면 수월리 산19-4
536    경남 산청군 금서면 특리 1300-127
537    경남 하동군 옥종면 돌고지로1088-51
538        경남 거제시 반송재로 68-37
539         제주 서귀포시 산록남로 2271
Name: Unnamed: 1, dtype: object

Shape of combined '소재지' data: (540,)

## Clean '소재지' data

### Subtask:
Clean the combined '소재지' data to handle missing values or inconsistencies.

**Reasoning**:
Check for and handle any missing values in the `combined_locations` Series. Replacing missing values with an empty string will prevent errors during the splitting process in the next step.

In [ ]:
# Check for missing values
print(f"Number of missing values in combined_locations: {combined_locations.isnull().sum()}")

# Replace missing values with empty strings to avoid errors during splitting
combined_locations_cleaned = combined_locations.fillna('')

print("\nHead of cleaned combined '소재지' data:")
display(combined_locations_cleaned.head())

print("\nTail of cleaned combined '소재지' data:")
display(combined_locations_cleaned.tail())

Number of missing values in combined_locations: 0

Head of cleaned combined '소재지' data:

0    서울특별시 성동구 성수1가 685-124
1       서울특별시 용산구 한남동 772-1
2       서울특별시 동작구 신대방동 산143
3        서울특별시 마포구 상암동 1538
4           서울특별시 강북구 번동 90
Name: Unnamed: 1, dtype: object

Tail of cleaned combined '소재지' data:

535     경남 거창군 가조면 수월리 산19-4
536    경남 산청군 금서면 특리 1300-127
537    경남 하동군 옥종면 돌고지로1088-51
538        경남 거제시 반송재로 68-37
539         제주 서귀포시 산록남로 2271
Name: Unnamed: 1, dtype: object

## Split '소재지' data

### Subtask:
Split the '소재지' strings into components like '광역시도', '시군구명', '읍면동명', and '상세주소'.

**Reasoning**:
Split the cleaned '소재지' strings using string methods and create a DataFrame with the split components. Given the structure of Korean addresses, splitting by space is a common approach, but may require further refinement depending on the address format. I'll split into a few columns initially and display the head to check the result.

In [ ]:
# Split the cleaned locations
# Splitting by space is a starting point, may need refinement
split_locations = combined_locations_cleaned.str.split(' ', n=3, expand=True)

# Name the columns based on the expected components
split_locations.columns = ['광역시도', '시군구명', '읍면동명', '상세주소']

print("Head of the split '소재지' data:")
display(split_locations.head())

print("\nTail of the split '소재지' data:")
display(split_locations.tail())

Head of the split '소재지' data:

    광역시도 시군구명  읍면동명     상세주소
0  서울특별시  성동구  성수1가  685-124
1  서울특별시  용산구   한남동    772-1
2  서울특별시  동작구  신대방동     산143
3  서울특별시  마포구   상암동     1538
4  서울특별시  강북구    번동       90

Tail of the split '소재지' data:

    광역시도  시군구명  읍면동명         상세주소
535   경남   거창군   가조면   수월리 산19-4
536   경남   산청군   금서면  특리 1300-127
537   경남   하동군   옥종면  돌고지로1088-51
538   경남   거제시  반송재로       68-37
539   제주  서귀포시  산록남로         2271

In [ ]:
# Take the first 540 entries from combined_list to match the number of rows in split_locations
aligned_combined_data = pd.Series(combined_list[:len(split_locations)], name='구분')

# Reset the index of split_locations to ensure alignment
split_locations_reset_index = split_locations.reset_index(drop=True)

# Concatenate the aligned_combined_data and the split_locations DataFrames
combined_df = pd.concat([aligned_combined_data, split_locations_reset_index], axis=1)

print("New DataFrame combining '구분' and split locations:")
display(combined_df.head())
display(combined_df.tail())
print(f"\nShape of the new combined DataFrame: {combined_df.shape}")

New DataFrame combining '구분' and split locations:

              구분   광역시도 시군구명  읍면동명     상세주소
0   서울숲공원 유아숲체험원  서울특별시  성동구  성수1가  685-124
1      한남 유아숲체험원  서울특별시  용산구   한남동    772-1
2   보라매공원 유아숲체험원  서울특별시  동작구  신대방동     산143
3   월드컵공원 유아숲체험원  서울특별시  마포구   상암동     1538
4  북서울꿈의숲 유아숲체험원  서울특별시  강북구    번동       90

            구분 광역시도  시군구명  읍면동명         상세주소
535   거창 치유의 숲   경남   거창군   가조면   수월리 산19-4
536   산청 치유의 숲   경남   산청군   금서면  특리 1300-127
537   하동 치유의 숲   경남   하동군   옥종면  돌고지로1088-51
538   거제 치유의 숲   경남   거제시  반송재로       68-37
539  서귀포 치유의 숲   제주  서귀포시  산록남로         2271

Shape of the new combined DataFrame: (540, 5)

In [ ]:
# Path to the first file
file_path = '/content/drive/MyDrive/2025 김진영교수 연구참여/산림복지사업군2차요청자료(0825)/부처별 사업정리.xlsx'

# Load sheet 5 again to get the original headers and columns
try:
    df_sheet5_original = pd.read_excel(file_path, sheet_name=4)
    print("Original sheet 5 loaded again.")
except FileNotFoundError:
    print(f"Error: File not found at {file_path}. Please check the path and upload the file to your Google Drive.")
    # Exit if file not found
    raise
except Exception as e:
    print(f"An error occurred while loading the original data: {e}")
    # Exit if loading fails
    raise

# Extract the header rows (first two rows) from the original df_sheet5_original
headers = df_sheet5_original.iloc[:2]

# Create a new DataFrame with the combined data and original columns,
# starting with the header rows and then adding empty rows for the data from combined_df
# The total number of rows will be the 2 header rows + the number of rows in combined_df (540)
total_rows = 2 + len(combined_df)
final_df = pd.DataFrame(index=range(total_rows), columns=df_sheet5_original.columns)

# Assign the header rows to the first two rows of final_df
final_df.iloc[:2] = headers.values

# Assign data from combined_df starting from the third row (index 2)
# Need to map columns from combined_df to final_df's columns
# Assuming the first 5 columns of final_df correspond to combined_df's columns ('구분', '광역시도', '시군구명', '읍면동명', '상세주소')
final_df.iloc[2:2+len(combined_df), :len(combined_df.columns)] = combined_df.values

# Replace df_sheet5 with the final DataFrame
df_sheet5 = final_df

print("df_sheet5 replaced with combined data and original headers:")
display(df_sheet5.head())
display(df_sheet5.tail())
print(f"\nShape of the new df_sheet5: {df_sheet5.shape}")

Original sheet 5 loaded again.
df_sheet5 replaced with combined data and original headers:

,구 분,광역시도,시군구명,읍면동명,상세주소,건립비\n(백만원),준공연도,건립 이후 운용 예산(백만원),Unnamed: 8,Unnamed: 9,...,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010.0,2011.0,2012.0,...,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010.0,2011.0,2012.0,...,2015.0,2016.0,2017.0,2018.0,2019.0,2020.0,2021.0,2022.0,2023.0,2024.0
2,서울숲공원 유아숲체험원,서울특별시,성동구,성수1가,685-124,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,한남 유아숲체험원,서울특별시,용산구,한남동,772-1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,보라매공원 유아숲체험원,서울특별시,동작구,신대방동,산143,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,구 분,광역시도,시군구명,읍면동명,상세주소,건립비\n(백만원),준공연도,건립 이후 운용 예산(백만원),Unnamed: 8,Unnamed: 9,...,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
537,거창 치유의 숲,경남,거창군,가조면,수월리 산19-4,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538,산청 치유의 숲,경남,산청군,금서면,특리 1300-127,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
539,하동 치유의 숲,경남,하동군,옥종면,돌고지로1088-51,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
540,거제 치유의 숲,경남,거제시,반송재로,68-37,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
541,서귀포 치유의 숲,제주,서귀포시,산록남로,2271,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Shape of the new df_sheet5: (542, 37)

# Task
Create a table with columns '항목', '준공연도', and '운용 예산(백만원)' from the sheet "4.산림교육치유활성화" in the file "/content/drive/MyDrive/2025 김진영교수 연구참여/2차 요청자료/부처별 사업정리_김준수(1-4).xlsx". The '운용 예산(백만원)' column should contain values from '각 준공연도' to 2024.

## Load the data

### Subtask:
Load the Excel file and specifically the "4.산림교육치유활성화" sheet.

**Reasoning**:
Define the file path and load the specified sheet from the Excel file into a pandas DataFrame, then display the head and shape of the DataFrame.

In [ ]:
file_path = '/content/drive/MyDrive/2025 김진영교수 연구참여/2차 요청자료/부처별 사업정리_김준수(1-4).xlsx'
sheet_name = '4.산림교육치유활성화'

try:
    df_forest = pd.read_excel(file_path, sheet_name=sheet_name)
    print(f"Data loaded successfully from sheet '{sheet_name}' of {file_path}")
    print(f"Sheet data shape: {df_forest.shape}")
    print("\nSheet Head:")
    display(df_forest.head())
except FileNotFoundError:
    print(f"Error: File not found at {file_path}. Please check the path and upload the file to your Google Drive.")
except Exception as e:
    print(f"An error occurred while loading the data: {e}")

Data loaded successfully from sheet '4.산림교육치유활성화' of /content/drive/MyDrive/2025 김진영교수 연구참여/2차 요청자료/부처별 사업정리_김준수(1-4).xlsx
Sheet data shape: (541, 37)

Sheet Head:

,구 분,광역시도,시군구명,읍면동명,상세주소,건립비\n(백만원),준공연도,건립 이후 운용 예산(백만원),Unnamed: 8,Unnamed: 9,...,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010.0,2011.0,2012.0,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
1,서울숲공원 유아숲체험원,서울특별시,성동구,성수1가,서울특별시 성동구 성수1가 685-124,100,2021년,NaN,NaN,NaN,...,-,-,-,-,-,-,1391,3521,3192,3475
2,한남 유아숲체험원,서울특별시,용산구,한남동,서울특별시 용산구 한남동 772-1,301,2015년,NaN,NaN,NaN,...,912,26879,21381,18000,15323,634,10349,29708,19412,21671
3,보라매공원 유아숲체험원,서울특별시,동작구,신대방동,서울특별시 동작구 신대방동 산143,200,2021년,NaN,NaN,NaN,...,-,-,-,-,-,-,3183,5149,13434,11759
4,월드컵공원 유아숲체험원,서울특별시,마포구,상암동,서울특별시 마포구 상암동 1538,200,2020년,NaN,NaN,NaN,...,-,-,-,-,-,4455,5824,8659,16794,18594

## Extract relevant columns

### Subtask:
Select the '항목', '준공연도', and the columns for '운용 예산(백만원)' from the loaded sheet.

**Reasoning**:
Select the '구 분' column as '항목', the '준공연도' column, and the range of columns from '건립 이후 운용 예산(백만원)' to 'Unnamed: 36' which represent the operating budget years from 2010 to 2024 from `df_forest`.

In [ ]:
# Select the '항목' column (assuming it's the first column)
item_column = df_forest['구 분']

# Select the '준공연도' column
completion_year_column = df_forest['준공연도']

# Identify the range of columns for '운용 예산(백만원)'
# Based on the head, the budget columns start from index 7 ('건립 이후 운용 예산(백만원)') up to index 36 ('Unnamed: 36' which corresponds to 2024)
budget_columns = df_forest.iloc[:, 7:37]

print("Head of selected '항목' column:")
display(item_column.head())

print("\nHead of selected '준공연도' column:")
display(completion_year_column.head())

print("\nHead of selected '운용 예산(백만원)' columns:")
display(budget_columns.head())

Head of selected '항목' column:

0             NaN
1    서울숲공원 유아숲체험원
2       한남 유아숲체험원
3    보라매공원 유아숲체험원
4    월드컵공원 유아숲체험원
Name: 구 분, dtype: object

Head of selected '준공연도' column:

0      NaN
1    2021년
2    2015년
3    2021년
4    2020년
Name: 준공연도, dtype: object

Head of selected '운용 예산(백만원)' columns:

,건립 이후 운용 예산(백만원),Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,...,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,2018.0,2019.0,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,1391,3521,3192,3475
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,912,26879,21381,18000,15323,634,10349,29708,19412,21671
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,3183,5149,13434,11759
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,4455,5824,8659,16794,18594

**Reasoning**:
The selected columns have been extracted. The next step is to create a new DataFrame with these columns to prepare for further processing.

In [ ]:
# Combine the selected columns into a new DataFrame
df_selected = pd.concat([item_column, completion_year_column, budget_columns], axis=1)

print("Head of the new DataFrame with selected columns:")
display(df_selected.head())

print("\nTail of the new DataFrame with selected columns:")
display(df_selected.tail())

Head of the new DataFrame with selected columns:

,구 분,준공연도,건립 이후 운용 예산(백만원),Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,...,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,NaN,NaN,2010.0,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0,2017.0,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
1,서울숲공원 유아숲체험원,2021년,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,1391,3521,3192,3475
2,한남 유아숲체험원,2015년,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,912,26879,21381,18000,15323,634,10349,29708,19412,21671
3,보라매공원 유아숲체험원,2021년,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,3183,5149,13434,11759
4,월드컵공원 유아숲체험원,2020년,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,4455,5824,8659,16794,18594

Tail of the new DataFrame with selected columns:

,구 분,준공연도,건립 이후 운용 예산(백만원),Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,...,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
536,거창 치유의 숲,2021년,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,587,4553,2560,2319
537,산청 치유의 숲,2022년,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,-,885,1422,3215
538,하동 치유의 숲,2023년,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,-,-,754,1580
539,거제 치유의 숲,2025년,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,-,-,-,-,-,-,-,-,-
540,서귀포 치유의 숲,2016년,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,1118,3682,3664,4389,2747,1128,4851,4572,5187

## Create the new table

### Subtask:
Construct a new DataFrame using the extracted columns, with '항목' and '준공연도' as direct columns and the budget columns transformed to represent '각 준공연도' to 2024.

**Reasoning**:
Drop the first two header rows, convert '준공연도' to numeric, identify budget columns, iterate through rows to select budget data from the completion year to 2024, and construct the final DataFrame with appropriate column names.

In [ ]:
# 1. Drop the first two rows of df_selected
df_cleaned = df_selected.iloc[2:].copy()

# 2. Convert the '준공연도' column to numeric
# Handle potential errors by coercing invalid parsing to NaN and removing '년'
df_cleaned['준공연도'] = pd.to_numeric(df_cleaned['준공연도'].astype(str).str.replace('년', '').str.strip(), errors='coerce')

# 3. Identify the columns that contain budget data (from the third column onwards)
# The first two columns are '구 분' and '준공연도'
budget_col_names = df_cleaned.columns[2:]

# Define the range of years for budget data based on the first row of the original df_selected
# The years are in the first row of the budget columns
budget_years_row = df_selected.iloc[0, 2:]
budget_years = pd.to_numeric(budget_years_row.astype(str).str.replace('.0', '', regex=False).str.strip(), errors='coerce')


# Map column names to years based on the extracted budget_years
col_to_year = {col_name: year for col_name, year in zip(budget_col_names, budget_years)}

# 4. & 5. Iterate through the rows and select relevant budget data
transformed_data = []

for index, row in df_cleaned.iterrows():
    item = row['구 분']
    completion_year = row['준공연도']

    # Ensure completion_year is a valid number
    if pd.isna(completion_year):
        # If completion year is missing or invalid, we cannot determine the budget range
        # Append None for budget values or handle as appropriate for the task
        # For this task, we will append empty list for budget values
        relevant_budget_values = []
    else:
        # Select budget columns for years >= completion_year and <= 2024
        relevant_budget_cols_for_row = [col for col in budget_col_names if col_to_year.get(col, float('inf')) >= completion_year and col_to_year.get(col, float('-inf')) <= 2024]
        relevant_budget_values = row[relevant_budget_cols_for_row].tolist()

    # 6. Append the transformed data for the row
    # Combine the item, completion year and the list of budget values into a single list
    transformed_data.append([item, completion_year, relevant_budget_values])

# Determine the maximum number of budget columns needed across all rows
# This is not needed anymore as the budget values are in a list within a single column

# Define the column names for the new DataFrame
new_column_names = ['구 분', '준공연도', '운용 예산(백만원)']


# 7. Create a new DataFrame from the transformed data list
df_transformed = pd.DataFrame(transformed_data, columns=new_column_names)


# 8. Column names are already defined in step 7

print("Head of the transformed DataFrame:")
display(df_transformed.head())

print("\nTail of the transformed DataFrame:")
display(df_transformed.tail())

print(f"\nShape of the transformed DataFrame: {df_transformed.shape}")

Head of the transformed DataFrame:

             구 분    준공연도                                         운용 예산(백만원)
0      한남 유아숲체험원  2015.0  [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...
1   보라매공원 유아숲체험원  2021.0     [nan, nan, nan, nan, 3183, 5149, 13434, 11759]
2   월드컵공원 유아숲체험원  2020.0  [nan, nan, nan, nan, nan, 4455, 5824, 8659, 16...
3  북서울꿈의숲 유아숲체험원  2021.0       [nan, nan, nan, nan, 3124, 4852, 3208, 5794]
4    숭인공원 유아숲체험원  2018.0  [nan, nan, nan, nan, nan, nan, nan, 6470, 8043...

Tail of the transformed DataFrame:

           구 분    준공연도                                         운용 예산(백만원)
534   거창 치유의 숲  2021.0        [nan, nan, nan, nan, 587, 4553, 2560, 2319]
535   산청 치유의 숲  2022.0                   [nan, nan, nan, 885, 1422, 3215]
536   하동 치유의 숲  2023.0                              [nan, nan, 754, 1580]
537   거제 치유의 숲  2025.0                                                 []
538  서귀포 치유의 숲  2016.0  [nan, nan, nan, nan, nan, nan, nan, nan, nan, ...

Shape of the transformed DataFrame: (539, 3)

In [ ]:
from google.colab import files

# Save the DataFrame to a CSV file
df_transformed.to_csv('df_transformed.csv', index=False, encoding='utf-8-sig')

# Provide a download link
files.download('df_transformed.csv')

In [ ]:
# Update the '운용 예산(백만원)' column
# Convert '준공연도' to string, remove '.0' and handle potential NaN values before combining with "~2024"
df_transformed['운용 예산(백만원)'] = df_transformed['준공연도'].astype(str).str.replace('.0', '', regex=False).replace('nan', '', regex=False) + '~2024'

print("DataFrame after updating '운용 예산(백만원)' column:")
display(df_transformed.head())
display(df_transformed.tail())

DataFrame after updating '운용 예산(백만원)' column:

             구 분    준공연도 운용 예산(백만원)
0      한남 유아숲체험원  2015.0  2015~2024
1   보라매공원 유아숲체험원  2021.0  2021~2024
2   월드컵공원 유아숲체험원  2020.0  2020~2024
3  북서울꿈의숲 유아숲체험원  2021.0  2021~2024
4    숭인공원 유아숲체험원  2018.0  2018~2024

           구 분    준공연도 운용 예산(백만원)
534   거창 치유의 숲  2021.0  2021~2024
535   산청 치유의 숲  2022.0  2022~2024
536   하동 치유의 숲  2023.0  2023~2024
537   거제 치유의 숲  2025.0  2025~2024
538  서귀포 치유의 숲  2016.0  2016~2024

# 25.10.31 - 25.11.10, 3차 요청자료 - 데이터 완성 요청

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# Path to the first file
file_path_B = '/content/drive/MyDrive/2025 김진영교수 연구참여/3차 요청자료/부처별 사업정리 (version 1).xlsx'
file_path_A = '/content/drive/MyDrive/2025 김진영교수 연구참여/3차 요청자료/템플릿_251030취합 (version 1).xlsx'

B = pd.read_excel(file_path_B, sheet_name=2).to_numpy()
A = pd.read_excel(file_path_A, sheet_name=4).to_numpy()

In [ ]:
B.shape, A.shape

((541, 37), (539, 38))

In [ ]:
set_A = set(A[2:,0])
set_B = set(B[1:,0])

print(len(A[2:,0]))
print(len(B[1:,0]))

537
540

In [ ]:
B[141,0] # 파랑새
B[142,0] # 무궁화 in B but not in A

'무궁화 유아숲체험원'

In [ ]:

B_except = np.delete(B, [141,142], axis=0)
B_except.shape

np.shares_memory(B_except, B)

False

In [ ]:
# Function to remove spaces from elements in a NumPy array slice
def clean_array_elements(arr_slice):
    # Convert to pandas Series to use string methods, handle potential non-string data
    series = pd.Series(arr_slice).astype(str).str.replace(' ', '', regex=False)
    return series.to_numpy()

# Clean the arrays by removing spaces
cleaned_A_col = clean_array_elements(A[:,0])
cleaned_B_except_col = clean_array_elements(B_except[:,0])

In [ ]:
cleaned_A_col.shape, cleaned_B_except_col.shape

((539,), (539,))

In [ ]:
strip_A = A.copy()
strip_B = B_except.copy()
strip_A.shape, strip_B.shape

strip_A[1:,0] = cleaned_A_col[1:]
strip_B[1:,0] = cleaned_B_except_col[1:]

array([[nan, nan, nan, ..., 2022, 2023, 2024],
       ['서울숲공원유아숲체험원', '서울특별시', '성동구', ..., 3521, 3192, 3475],
       ['한남유아숲체험원', '서울특별시', '용산구', ..., 29708, 19412, 21671],
       ...,
       ['하동치유의숲', '경남', '하동군', ..., '-', 754, 1580],
       ['거제치유의숲', '경남', '거제시', ..., '-', '-', '-'],
       ['서귀포치유의숲', '제주', '서귀포시', ..., 4851, 4572, 5187]], dtype=object)

In [ ]:
strip_B[538,1]

'제주'

In [ ]:
np.concatenate(strip_B, np.zeros(len(strip_B),None), axis=1)
strip_B.shape

Shape of strip_B after adding a column of zeros:
(539, 38)

In [ ]:
for i in range(1, len(strip_B)):
    value_B = strip_B[i, 0]
    for j in range(1, len(strip_A)):
        value_A = strip_A[j, 0]
        if value_B == value_A:
          strip_B[i, :] = strip_A[j, :]

In [ ]:
strip

array([[nan, nan, nan, ..., 2023, 2024, 0.0],
       ['서울숲공원유아숲체험원', '서울특별시', '성동구', ..., 3192, 3475, 'no'],
       ['한남유아숲체험원', '서울특별시', '용산구', ..., 19412, 21671, 'no'],
       ...,
       ['하동치유의숲', '경남', '하동군', ..., 754, 1580, 'no'],
       ['거제치유의숲', '경남', '거제시', ..., '-', '-', 'no'],
       ['서귀포치유의숲', '제주', '서귀포시', ..., 4572, 5187, 'no']], dtype=object)

## 1.1 Sort

In [ ]:
file_path_B = '/content/drive/MyDrive/2025 김진영교수 연구참여/3차 요청자료/부처별 사업정리 (version 1).xlsx'
B = pd.read_excel(file_path_B, sheet_name=2).to_numpy()

In [ ]:
# Get the unique values from B[1:,1] and sort them

# Get the unique values using np.unique or by converting to a set
unique_values_B = np.unique(B[1:,1])

# Convert the unique values to a list and sort it
# Although np.unique already returns a sorted array,
# converting to a list and sorting explicitly ensures it's a standard Python list
# and handles potential data types gracefully if needed.
sorted_unique_values_B = sorted(unique_values_B.tolist())


print("Original values in B[1:,1]:")
print(B[1:,1])

print("\nSorted unique values from B[1:,1]:")
print(sorted_unique_values_B)

# You can also print the number of unique values
print(f"\nNumber of unique values: {len(sorted_unique_values_B)}")

Original values in B[1:,1]:
['서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시'
 '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '전라남도'
 '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '경기도' '서울특별시' '서울특별시'
 '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시'
 '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시'
 '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시'
 '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시'
 '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시' '서울특별시'
 '서울특별시' '부산광역시' '부산광역시' '부산광역시' '부산광역시' '부산광역시' '부산광역시' '부산광역시' '부산광역시'
 '부산광역시' '부산광역시' '대구광역시' '대구광역시' '대구광역시' '대구광역시' '대구광역시' '대구광역시' '대구광역시'
 '대구광역시' '대구광역시' '대구광역시' '인천광역시' '인천광역시' '인천광역시' '인천광역시' '인천광역시' '인천광역시'
 '인천광역시' '인천광역시' '인천광역시' '인천광역시' '인천광역시' '인천광역시' '인천광역시' '인천광역시' '인천광역시'
 '인천광역시' '인천광역시' '인천광역시' '강원특별자치도' '인천광역시' '광주광역시' '광주광역시' '광주광역시' '광주광역시'
 '광주광역시' '광주광역시' '광주광역시' '광주광역시' '광주광역시' '광주광역시' '광주광역시' '대전광역시' '대전광역시'
 '대전광역시' '대전광역시' '대전광역시' '대전광역시' '경상남도' '대전광역시' '대전광역시' '대전광역시' '대전광역시'
 '대전광역시' '대전광역시' '울산광역시' '충청남도' '울산광역시' '경기도' '경기도' '경기도' '경기도' '경기도'
 '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도'
 '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도'
 '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도'
 '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도'
 '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도'
 '경기도' '경기도' '경기도' '경상북도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도'
 '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도' '경기도'
 '경기도' '경기도' '경기도' '경기도' '강원도특별자치도' '강원도특별자치도' '강원도특별자치도' '강원도특별자치도'
 '강원도특별자치도' '강원도특별자치도' '강원도특별자치도' '강원도특별자치도' '충청남도' '강원도특별자치도' '강원도특별자치도'
 '강원도특별자치도' '강원도특별자치도' '강원도특별자치도' '강원도특별자치도' '강원도특별자치도' '충청북도' '충청북도'
 '충청북도' '충청북도' '충청북도' '충청북도' '충청북도' '충청북도' '충청북도' '충청북도' '충청북도' '충청남도'
 '충청남도' '충청남도' '충청남도' '충청남도' '충청남도' '충청남도' '충청남도' '충청남도' '충청남도' '충청남도'
 '충청남도' '충청남도' '충청남도' '충청남도' '충청남도' '충청남도' '충청남도' '충청남도' '충청남도' '충청남도'
 '충청남도' '충청남도' '충청남도' '충청남도' '충청남도' '전북특별자치도' '전북특별자치도' '전북특별자치도'
 '전북특별자치도' '전북특별자치도' '전북특별자치도' '전북특별자치도' '전북특별자치도' '전북특별자치도' '전북특별자치도'
 '전북특별자치도' '전북특별자치도' '전북특별자치도' '전북특별자치도' '경상남도' '전라남도' '전라남도' '전라남도'
 '전라남도' '전라남도' '전라남도' '전라남도' '전라남도' '전라남도' '전라남도' '전라남도' '전라남도' '전라남도'
 '전라남도' '전라남도' '전라남도' '전라남도' '전라남도' '전라남도' '전라남도' '전라남도' '전라남도' '전라남도'
 '전라남도' '전라남도' '전라남도' '전라남도' '전라남도' '전라남도' '경상북도' '경상북도' '경상북도' '경상북도'
 '경상북도' '경상북도' '경상북도' '경상북도' '경상북도' '경상북도' '경상북도' '경상북도' '경상북도' '경상북도'
 '경상북도' '경상북도' '경상북도' '경상북도' '경상북도' '경상북도' '경상북도' '경상북도' '경상북도' '경상남도'
 '경상남도' '경상남도' '경상남도' '경상남도' '경상남도' '경상남도' '경상남도' '경상남도' '경상남도' '경상남도'
 '경상남도' '경상남도' '경상남도' '경상남도' '경상남도' '경상남도' '경상남도' '경상남도' '경상남도' '경상남도'
 '경상남도' '경상남도' '경상남도' '경상남도' '경상남도' '경상남도' '경상남도' '경상남도' '경상남도' '경상남도'
 '경상남도' '제주특별자치도' '제주특별자치도' '제주특별자치도' '제주특별자치도' '제주특별자치도' '제주특별자치도'
 '강원특별자치도' '강원특별자치도' '강원특별자치도' '강원특별자치도' '강원특별자치도' '강원특별자치도' '강원특별자치도'
 '강원특별자치도' '서울특별시' '경기도' '인천광역시' '경기도' '경기도' '경기도' '인천광역시' '경기도' '인천광역시'
 '경기도' '서울특별시' '경기도' '경기도' '경기도' '강원특별자치도' '강원특별자치도' '강원특별자치도' '강원특별자치도'
 '강원특별자치도' '강원특별자치도' '강원특별자치도' '강원특별자치도' '강원특별자치도' '강원특별자치도' '강원특별자치도'
 '강원특별자치도' '강원특별자치도' '강원특별자치도' '강원특별자치도' '강원특별자치도' '강원특별자치도' '경상북도'
 '부산광역시' '울산광역시' '경상북도' '경상북도' '경상북도' '경상북도' '경상북도' '경상남도' '경상북도'
 '경상북도영천시' '경상북도' '경상남도' '경상북도' '경상북도' '경상남도' '부산광역시' '경상남도' '전북특별자치도'
 '전라남도' '전북특별자치도' '경상남도' '전북특별자치도' '광주광역시' '전라남도' '전북특별자치도' '전라남도' '경상남도'
 '전라남도' '제주특별자치도' '전라남도' '전라남도' '충청북도' '충청북도' '충청북도' '충청북도' '충청북도' '충청북도'
 '충청남도' '대전광역시' '충청남도' '세종특별자치시' '충청남도' '충청남도' '충청남도' '대전광역시' '충청북도'
 '전라남도' '충청남도' '충청북도' '경상북도' '대전광역시' '강원특별지치도' '강원특별자치도' '경기' '경기' '강원'
 '강원' '충남' '충북' '전남' '전남' '전남' '전북' '울산' '부산' '경북' '경기' '경기' '경기' '경기'
 '경기' '강원' '강원' '대전' '충북' '충북' '충북' '충북' '충북' '충북' '충남' '충남' '충남' '충남'
 '전북' '전북' '전남' '전남' '전남' '전남' '전남' '전남' '전남' '전남' '부산' '대구' '대구' '경북'
 '경북' '경남' '경남' '경남' '경남' '경남' '경남' '경남' '제주' '세종특별자치시' '세종특별자치시']

Sorted unique values from B[1:,1]:
['강원', '강원도특별자치도', '강원특별자치도', '강원특별지치도', '경기', '경기도', '경남', '경북', '경상남도', '경상북도', '경상북도영천시', '광주광역시', '대구', '대구광역시', '대전', '대전광역시', '부산', '부산광역시', '서울특별시', '세종특별자치시', '울산', '울산광역시', '인천광역시', '전남', '전라남도', '전북', '전북특별자치도', '제주', '제주특별자치도', '충남', '충북', '충청남도', '충청북도']

Number of unique values: 33

In [ ]:
# Sort the entire B array based on the values in the second column (index 1)
# We will sort based on the rows starting from index 1, assuming the first row is a header

# Get the indices that would sort the second column (from the second row onwards)
# We need to handle potential non-sortable types if they exist in the column
try:
    sort_indices = np.argsort(B[1:, 1].astype(str)) # Convert to string for consistent comparison
except Exception as e:
    print(f"Error getting sort indices: {e}")
    print("Attempting to sort based on original data types, might cause unexpected results.")
    sort_indices = np.argsort(B[1:, 1])


# Apply the sorted indices to reorder the rows of B, starting from the second row
# The header row (index 0) will remain at the top
sorted_B = np.vstack((B[0, :], B[1:, :][sort_indices]))

# Replace the original B with the sorted array
B = sorted_B

print("B array sorted based on the second column.")
print("\nFirst 5 rows of the sorted B array:")
display(B[:5])

print("\nLast 5 rows of the sorted B array:")
display(B[-5:])

B array sorted based on the second column.

First 5 rows of the sorted B array:

array([[nan, nan, nan, nan, nan, nan, nan, 2010, 2011, 2012, 2013, 2014,
        2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2010,
        2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021,
        2022, 2023, 2024, nan],
       ['대관령치유의숲', '강원', '강릉시', '성산면', '강원 강릉시 성산면 대관령옛길 127-42', 7400,
        '2016년', '-', '-', '-', '-', '-', '-', nan, nan, 167, 167, 167,
        167, 167, 167, 167, nan, nan, nan, nan, nan, '-', 1115, 2171,
        6197, 8260, 3402, 1867, 9296, 8719, 7121, 'yes'],
       ['망경대산치유의숲', '강원', '영월군', '중동면', '강원 영월군 중동면 선도우길 177', 2100,
        '2018년', '-', '-', '-', '-', '-', '-', '-', '-', 0, 0, 0, 0, 2,
        2, 2, nan, nan, nan, nan, nan, '-', '-', '-', 2484, 3618, 4325,
        224, 1844, 1411, 2013, 'no'],
       ['삼척활기치유의숲', '강원', '삼척시', '미로면', '강원 삼척시 미로면 활기리 산34', 5000,
        '2020년', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-', 137,
        253, 302, 311, 285, nan, nan, nan, nan, nan, '-', '-', '-', '-',
        '-', 363, 641, 2353, 2196, 2444, 'no'],
       ['청태산치유의숲', '강원', '횡성군', '둔내면', '강원 횡성군 둔내면 청태산로 777', 2111,
        '2011년', '-', '-', 118, 192, 192, 197, 213, 167, 167, 167, 167,
        167, 167, 167, 167, nan, nan, nan, nan, nan, 3991, 11498, 26176,
        22819, 31073, 6880, 10584, 22229, 25392, 43107, 'yes']],
      dtype=object)

Last 5 rows of the sorted B array:

array([['솔밭모험의숲유아숲체험원', '충청북도', '청주시', '흥덕구', '충청북도 청주시 흥덕구 송정동 산8-4',
        152, '2015년', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
        51, 51, 84, 87, 60, nan, nan, nan, nan, nan, 0, 0, 0, 0, 0, 518,
        3726, 4827, 3455, 4071, 'no'],
       ['수안보유아숲체험원', '충청북도', '충주시', '수안보면', '충청북도 충주시 수안보면 수회리 산39-1',
        148, '2024년', '-', '-', '-', '-', '-', '-', '-', '-', '-', '-',
        '-', '-', '-', '-', 65, nan, nan, nan, nan, nan, '-', '-', '-',
        '-', '-', '-', '-', '-', '-', 2884, 'yes'],
       ['생거진천유아숲체험원', '충청북도', '진천군', '백곡면', '충청북도 진천군 백곡면 명암리 산34-1',
        350, '2015년', '-', '-', '-', '-', '-', '-', '-', '-', '-', 50,
        71, 51, 56, 57, 59, nan, nan, nan, nan, nan, 0, 0, 0, 0, 4247,
        1360, 2500, 1854, 1857, 3079, 'no'],
       ['상당산성자연휴양림유아숲체험원', '충청북도', '청주시', '청원구',
        '충청북도 청주시 청원구 내수읍 덕암2길 162', 148, '2017년', '-', '-', '-', '-',
        '-', '-', 121, 163, 148, 278, 355, 331, 345, 374, 354, nan, nan,
        nan, nan, nan, '-', '-', 1554, 8722, 9463, 3347, 4583, 7794,
        8435, 5767, 'yes'],
       ['솔솔솔도토리숲유아숲체험원', '충청북도', '단양군', '단양읍', '충청북도 단양군 단양읍 도담리 산4-29',
        148, '2016년', '-', '-', '-', '-', '-', '-', 15, 17, 42, 65, 71,
        56, 53, 57, 118, nan, nan, nan, nan, nan, '-', 4096, 8957, 13838,
        4423, 1516, 7980, 5534, 3678, 2884, 'yes']], dtype=object)

In [ ]:
B

array([[nan, nan, nan, ..., 2023, 2024, nan],
       ['대관령치유의숲', '강원', '강릉시', ..., 8719, 7121, 'yes'],
       ['망경대산치유의숲', '강원', '영월군', ..., 1411, 2013, 'no'],
       ...,
       ['생거진천유아숲체험원', '충청북도', '진천군', ..., 1857, 3079, 'no'],
       ['상당산성자연휴양림유아숲체험원', '충청북도', '청주시', ..., 8435, 5767, 'yes'],
       ['솔솔솔도토리숲유아숲체험원', '충청북도', '단양군', ..., 3678, 2884, 'yes']],
      dtype=object)

#2.1 국립자연휴양림 이름 붙이기 (구분 열 넣기)

In [7]:
file_path_B = '/content/drive/MyDrive/2025 김진영교수 연구참여/25년 산림복지분야 심층평가 추가 요구자료(국립자연휴양림관리소).xlsx'
B = pd.read_excel(file_path_B).to_numpy()

In [ ]:
import io
import pandas as pd
C = pd.read_csv(io.StringIO('''
유명산,경기 가평 설악 유명산길 79-53
산음,경기 양평 단월 고북길 347
중미산,경기 양평 옥천 신복리 산201-2
운악산,경기 포천 화현 화동로 184번길 39
속리산말티재,충북 보은 장안 속리산로 256
오서산,충남 보령 청라 오서산길 531
희리산해송,충남 서천 종천 희리산길 206
용현,충남 서산 운산 용현 산2-37
상당산성,충북 청주 청원 내수 덕암2길 162
아세안,경기 양주 백석 기산로 472
무의도,인천 중구 무의 산151-1
청태산,강원 횡성 둔내 청태산로 610
복주산,강원 철원 근남 하오재로 818
용화산,강원 춘천 사북 사여골길 294
백운산,강원 원주 판부 백운산길 81
삼봉,강원 홍천 내 삼봉휴양길 276
용대,강원 인제 북 연화동길 251
방태산,강원 인제 기린 방태산길 377
대관령,강원 강릉 성산 삼포암길 133
미천골,강원 양양 서 미천골길 115
두타산,강원 평창 진부 아차골길 132
가리왕산,강원 정선 정선 가리왕산로 707
검봉산,강원 삼척 원덕 임원안길525-145
화천야영장,강원 화천 간동 배후령길 1144
대야산,경북 문경 가은 용추길 31-35
칠보산,경북 영덕 병곡 칠보산길 587
청옥산,경북 봉화 청옥로 1552-163
검마산,경북 영양 수비 검마산길 191
통고산,경북 울진 서 불영계곡로 880
운문산,경북 청도 운문 운문로 763
신불산폭포,울산 울주 상북 청수골길 175
김천야영장,경북 김천 대덕 조룡 865
황정산,충북 단양 대강 황정산로 239-11
달음산,부산 기장 일광 화용길 299-106
용지봉,경남 김해시 대청계곡길 170-36
방장산,전남 장성 북이 방장로 353
덕유산,전북 무주 무풍 구천동로 530-62
운장산,전북 진안 정천 휴양림길 77
지리산,경남 함양 마천 음정길 152
남해편백,경남 남해 삼동 금암로 658
회문산,전북 순창 구림 안심길 295
천관산,전남 장흥 관산 칠관로 842-1150
낙안민속,전남 순천 낙안 민속마을길 1600
변산,전북 부안 변산 변산로 3768
진도,전남 진도 임회 동령개길 1-92
신시도,전북 군산 옥도 신시도길 271
'''), header=None)

In [ ]:
B[1:,0], C[:,0]

(array(['유명산', nan, nan, '중미산', nan, nan, nan, nan, nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, '산음', nan, nan, nan, nan,
        nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
        nan, '진도', nan, nan, '신시도', nan, nan, nan, nan, nan, nan, nan, nan,
        nan], dtype=object),
 array(['유명산', '산음', '중미산', '운악산', '속리산말티재', '오서산', '희리산해송', '용현', '상당산성',
        '아세안', '무의도', '청태산', '복주산', '용화산', '백운산', '삼봉', '용대', '방태산', '대관령',
        '미천골', '두타산', '가리왕산', '검봉산', '화천야영장', '대야산', '칠보산', '청옥산', '검마산',
        '통고산', '운문산', '신불산폭포', '김천야영장', '황정산', '달음산', '용지봉', '방장산', '덕유산',
        '운장산', '지리산', '남해편백', '회문산', '천관산', '낙안민속', '변산', '진도', '신시도'],
       dtype=object))

In [ ]:
for i in range(1,48):
  val_B = B[i, 4]
  for j in range(0,len(C[:,1])):
    val_C = C[j,1]
    if val_B == val_C:
      B[i,0] = C[j,0]

In [ ]:
B.shape

(53, 36)

In [ ]:
import pandas as pd
from google.colab import files

# Convert the entire NumPy array B to a pandas DataFrame
# You might want to specify column names if you have them, or use the first row as headers if applicable
df_B_full = pd.DataFrame(B)

# Define the output file name
output_filename = 'B_full_data.csv' # Naming it to indicate it's the full data

# Save the DataFrame to a CSV file
# You might want to exclude the index if it's just a default index
df_B_full.to_csv(output_filename, index=False, encoding='utf-8-sig')

# Provide a download link for the file
files.download(output_filename)

print(f"'{output_filename}' has been created and is ready for download.")

'B_full_data.csv' has been created and is ready for download.

In [19]:
file_path_B = '/content/drive/MyDrive/2025 김진영교수 연구참여/25년 산림복지분야 심층평가 추가 요구자료(국립자연휴양림관리소).xlsx'
B = pd.read_excel(file_path_B).to_numpy()

In [25]:
import io
import pandas as pd
full_adress = B[4:,1]

full_adress.shape

(47,)

In [29]:
# 광역시도a, 시군구명b, 읍면동면c, 상세주소(전체)
# Initialize lists to store the split parts
a_list = [] # 광역시도
b_list = [] # 시군구명
c_list = [] # 읍면동명
d_list = [] # 상세주소 (remaining parts)

for address_str in full_adress:
    # Split the address string by space, limiting to 3 splits
    # This ensures that any remaining parts of the address stay together in the last element
    parts = address_str.split(' ', 3)

    # Append parts to respective lists, handling cases where there might be fewer than 4 parts
    a_list.append(parts[0] if len(parts) > 0 else '')
    b_list.append(parts[1] if len(parts) > 1 else '')
    c_list.append(parts[2] if len(parts) > 2 else '')
    d_list.append(parts[3] if len(parts) > 3 else '')

# Convert lists to numpy arrays
a = np.array(a_list)
b = np.array(b_list)
c = np.array(c_list)
d = np.array(d_list)

print("광역시도 (a):")
print(a)
print("\n시군구명 (b):")
print(b)
print("\n읍면동명 (c):")
print(c)
print("\n상세주소 (d):")
print(d)

광역시도 (a):
['경기' '경기' '경기' '경기' '충북' '충남' '충남' '충남' '충북' '경기도' '인천' '충남' '강원' '강원'
 '강원' '강원' '강원' '강원' '강원' '강원' '강원' '강원' '강원' '강원' '강원' '경북' '경북' '경북'
 '경북' '경북' '경북' '울산' '경북' '충북' '부산' '경남' '전남' '전북' '전북' '경남' '경남' '전북'
 '전남' '전남' '전북' '전남' '전북']

시군구명 (b):
['가평' '양평' '양평' '포천' '보은' '보령' '서천' '서산' '청주' '양주시' '중구' '금산군' '횡성' '철원'
 '춘천' '원주' '홍천' '인제' '인제' '강릉' '양양' '평창' '정선' '삼척' '화천' '문경' '영덕' '봉화'
 '영양' '울진' '청도' '울주' '김천' '단양' '기장군' '김해시' '장성' '무주' '진안' '함양' '남해' '순창'
 '장흥' '순천' '부안군' '진도' '군산시']

읍면동명 (c):
['설악' '단월' '옥천' '화현' '장안' '청라' '종천' '운산' '청원' '백석읍' '무의' '남이면' '둔내' '근남'
 '사북' '판부' '내' '북' '기린' '성산' '서' '진부' '정선' '원덕' '간동' '가은' '병곡' '청옥로' '수비'
 '서' '운문' '상북' '대덕' '대강' '일광면' '대청계곡길' '북이' '무풍' '정천' '마천' '삼동' '구림' '관산'
 '낙안' '변산면' '임회면' '옥도면']

상세주소 (d):
['유명산길 79-53' '고북길 347' '신복리 산201-2' '화동로 184번길 39' '속리산로 256' '오서산길 531'
 '희리산길 206' '용현 산2-37' '내수 덕암2길 162' '기산로 472' '산151-1' '거북바위길 10-163'
 '청태산로 610' '하오재로 818' '사여골길 294' '백운산길 81' '삼봉휴양길 276' '연화동길 251'
 '방태산길 377' '삼포암길 133' '미천골길 115' '아차골길 132' '가리왕산로 707' '임원안길 525-145 '
 '배후령길 1144' '용추길 31-35' '칠보산길 587' '1552-163' '검마산길 191' '불영계곡로 880'
 '운문로 763' '청수골길 175' '조룡 865' '황정산로 239-11' '화용길 299-106' '170-36'
 '방장로 353' '구천동로 530-62' '휴양림길 77' '음정길 152' '금암로 658' '안심길 295'
 '칠관로 842-1150' '민속마을길 1600' '변산로 3768' '동령개길 1-92' '신시도길 271']

In [28]:
full_adress

array(['경기 가평 설악 유명산길 79-53', '경기 양평 단월 고북길 347', '경기 양평 옥천 신복리 산201-2',
       '경기 포천 화현 화동로 184번길 39', '충북 보은 장안 속리산로 256', '충남 보령 청라 오서산길 531',
       '충남 서천 종천 희리산길 206', '충남 서산 운산 용현 산2-37', '충북 청주 청원 내수 덕암2길 162',
       '경기도 양주시 백석읍 기산로 472', '인천 중구 무의 산151-1',
       '충남 금산군 남이면 거북바위길 10-163', '강원 횡성 둔내 청태산로 610',
       '강원 철원 근남 하오재로 818', '강원 춘천 사북 사여골길 294', '강원 원주 판부 백운산길 81',
       '강원 홍천 내 삼봉휴양길 276', '강원 인제 북 연화동길 251', '강원 인제 기린 방태산길 377',
       '강원 강릉 성산 삼포암길 133', '강원 양양 서 미천골길 115', '강원 평창 진부 아차골길 132',
       '강원 정선 정선 가리왕산로 707', '강원 삼척 원덕 임원안길 525-145 ',
       '강원 화천 간동 배후령길 1144', '경북 문경 가은 용추길 31-35', '경북 영덕 병곡 칠보산길 587',
       '경북 봉화 청옥로 1552-163', '경북 영양 수비 검마산길 191', '경북 울진 서 불영계곡로 880',
       '경북 청도 운문 운문로 763', '울산 울주 상북 청수골길 175', '경북 김천 대덕 조룡 865',
       '충북 단양 대강 황정산로 239-11', '부산 기장군 일광면 화용길 299-106',
       '경남 김해시 대청계곡길 170-36', '전남 장성 북이 방장로 353', '전북 무주 무풍 구천동로 530-62',
       '전북 진안 정천 휴양림길 77', '경남 함양 마천 음정길 152', '경남 남해 삼동 금암로 658',
       '전북 순창 구림 안심길 295', '전남 장흥 관산 칠관로 842-1150', '전남 순천 낙안 민속마을길 1600',
       '전북 부안군 변산면 변산로 3768', '전남 진도 임회면 동령개길 1-92',
       '전북 군산시 옥도면 신시도길 271'], dtype=object)

In [38]:
# Reshape a, b, and c into column vectors
a_col = a.reshape(-1, 1)
b_col = b.reshape(-1, 1)
c_col = c.reshape(-1, 1)
full_adress_col = full_adress.reshape(-1,1)

# Concatenate them horizontally (column-wise)
concatenated_abc_cols = np.concatenate((a_col, b_col, c_col, full_adress_col), axis=1)

print("Concatenated array (a, b, c) as columns (first 5 rows):")
print(concatenated_abc_cols[:5])
print("\nShape of the concatenated array:")
print(concatenated_abc_cols.shape)

Concatenated array (a, b, c) as columns (first 5 rows):
[['경기' '가평' '설악' '경기 가평 설악 유명산길 79-53']
 ['경기' '양평' '단월' '경기 양평 단월 고북길 347']
 ['경기' '양평' '옥천' '경기 양평 옥천 신복리 산201-2']
 ['경기' '포천' '화현' '경기 포천 화현 화동로 184번길 39']
 ['충북' '보은' '장안' '충북 보은 장안 속리산로 256']]

Shape of the concatenated array:
(47, 4)

In [39]:
three = concatenated_abc_cols

In [40]:
three

array([['경기', '가평', '설악', '경기 가평 설악 유명산길 79-53'],
       ['경기', '양평', '단월', '경기 양평 단월 고북길 347'],
       ['경기', '양평', '옥천', '경기 양평 옥천 신복리 산201-2'],
       ['경기', '포천', '화현', '경기 포천 화현 화동로 184번길 39'],
       ['충북', '보은', '장안', '충북 보은 장안 속리산로 256'],
       ['충남', '보령', '청라', '충남 보령 청라 오서산길 531'],
       ['충남', '서천', '종천', '충남 서천 종천 희리산길 206'],
       ['충남', '서산', '운산', '충남 서산 운산 용현 산2-37'],
       ['충북', '청주', '청원', '충북 청주 청원 내수 덕암2길 162'],
       ['경기도', '양주시', '백석읍', '경기도 양주시 백석읍 기산로 472'],
       ['인천', '중구', '무의', '인천 중구 무의 산151-1'],
       ['충남', '금산군', '남이면', '충남 금산군 남이면 거북바위길 10-163'],
       ['강원', '횡성', '둔내', '강원 횡성 둔내 청태산로 610'],
       ['강원', '철원', '근남', '강원 철원 근남 하오재로 818'],
       ['강원', '춘천', '사북', '강원 춘천 사북 사여골길 294'],
       ['강원', '원주', '판부', '강원 원주 판부 백운산길 81'],
       ['강원', '홍천', '내', '강원 홍천 내 삼봉휴양길 276'],
       ['강원', '인제', '북', '강원 인제 북 연화동길 251'],
       ['강원', '인제', '기린', '강원 인제 기린 방태산길 377'],
       ['강원', '강릉', '성산', '강원 강릉 성산 삼포암길 133'],
       ['강원', '양양', '서', '강원 양양 서 미천골길 115'],
       ['강원', '평창', '진부', '강원 평창 진부 아차골길 132'],
       ['강원', '정선', '정선', '강원 정선 정선 가리왕산로 707'],
       ['강원', '삼척', '원덕', '강원 삼척 원덕 임원안길 525-145 '],
       ['강원', '화천', '간동', '강원 화천 간동 배후령길 1144'],
       ['경북', '문경', '가은', '경북 문경 가은 용추길 31-35'],
       ['경북', '영덕', '병곡', '경북 영덕 병곡 칠보산길 587'],
       ['경북', '봉화', '청옥로', '경북 봉화 청옥로 1552-163'],
       ['경북', '영양', '수비', '경북 영양 수비 검마산길 191'],
       ['경북', '울진', '서', '경북 울진 서 불영계곡로 880'],
       ['경북', '청도', '운문', '경북 청도 운문 운문로 763'],
       ['울산', '울주', '상북', '울산 울주 상북 청수골길 175'],
       ['경북', '김천', '대덕', '경북 김천 대덕 조룡 865'],
       ['충북', '단양', '대강', '충북 단양 대강 황정산로 239-11'],
       ['부산', '기장군', '일광면', '부산 기장군 일광면 화용길 299-106'],
       ['경남', '김해시', '대청계곡길', '경남 김해시 대청계곡길 170-36'],
       ['전남', '장성', '북이', '전남 장성 북이 방장로 353'],
       ['전북', '무주', '무풍', '전북 무주 무풍 구천동로 530-62'],
       ['전북', '진안', '정천', '전북 진안 정천 휴양림길 77'],
       ['경남', '함양', '마천', '경남 함양 마천 음정길 152'],
       ['경남', '남해', '삼동', '경남 남해 삼동 금암로 658'],
       ['전북', '순창', '구림', '전북 순창 구림 안심길 295'],
       ['전남', '장흥', '관산', '전남 장흥 관산 칠관로 842-1150'],
       ['전남', '순천', '낙안', '전남 순천 낙안 민속마을길 1600'],
       ['전북', '부안군', '변산면', '전북 부안군 변산면 변산로 3768'],
       ['전남', '진도', '임회면', '전남 진도 임회면 동령개길 1-92'],
       ['전북', '군산시', '옥도면', '전북 군산시 옥도면 신시도길 271']], dtype=object)

In [ ]:
다운받자

In [41]:
import pandas as pd
from google.colab import files

# Convert the NumPy array 'three' to a pandas DataFrame
df_three = pd.DataFrame(three, columns=['광역시도', '시군구명', '읍면동명', '상세주소'])

# Define the output file name
output_filename = 'three_address_data.csv'

# Save the DataFrame to a CSV file
df_three.to_csv(output_filename, index=False, encoding='utf-8-sig')

# Provide a download link for the file
files.download(output_filename)

print(f"'{output_filename}' has been created and is ready for download.")

'three_address_data.csv' has been created and is ready for download.